---
name: "YouTube Audio"
guid: "7323ea64-a200-4265-ab8f-e7ae27d06c38"
version: "10.11.5"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Download YouTube audio directly to a Jellyfin Music Library."
description: >
  YouTube Audio lets you download YouTube audio (single videos or playlists) as Opus, MP3, or M4A files,
  review and edit metadata in a staging area, then push files into your Jellyfin music library.
  Uses yt-dlp for downloading and TagLibSharp for metadata tagging.
category: "Music"
imageUrl: "https://raw.githubusercontent.com/JPKribs/jellyfin-plugin-youtubeaudio/refs/heads/master/Jellyfin.Plugin.YouTubeAudio/Assets/Logo.png"
owner: "JPKribs"
artifacts:
- "Jellyfin.Plugin.YouTubeAudio.dll"
- "YoutubeDLSharp.dll"
- "TagLibSharp.dll"
changelog:
  chores:
  - Set category to "Music"